### ISSUE TITLE
OverflowError: math range error

### ISSUE THREAD

**Issue by wasiahmad** [OpenNMT/OpenNMT-py#749] opened 2018-06-06 05:31 UTC
Getting the following error while running inference on the pre-trained transformer for summarization task.

> Traceback (most recent call last):
>   File "translate.py", line 29, in <module>
>     main(opt)
>   File "translate.py", line 18, in main
>     opt.batch_size, opt.attn_debug)
>   File "/home/wasiahmad/workspace/projects/OpenNMT-py/onmt/translate/Translator.py", line 200, in translate
>     self._report_score('PRED', pred_score_total, pred_words_total)
>   File "/home/wasiahmad/workspace/projects/OpenNMT-py/onmt/translate/Translator.py", line 394, in _report_score
>     name, math.exp(-score_total / words_total)))
> OverflowError: math range error

**Comment by srush** [comment] 2018-06-18 13:19
can you post your code?

**Comment by wasiahmad** [comment] 2018-06-19 16:59
I didn't make any changes to the original code. The error occurs in [this function](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/Translator.py#L415) and precisely when the `math.exp()` function is used.

**Comment by vince62s** [comment] 2018-08-03 11:50
closing this, reopen if needed

**Comment by vince62s** [comment] 2018-08-31 14:39
I replicate this error while translating a summarization model.

python3 translate.py -gpu 0 -model exp/$model -stepwise_penalty -coverage_penalty summary\
    -beta 5 -length_penalty wu -alpha 0.9 -block_ngram_repeat 3 -ignore_when_blocking "." "</s>" "<s>" \
    -src $VALID_SRC.10000 -output $VALID_HYP -beam_size $bs -batch_size 12

**Comment by laniger** [comment] 2018-09-13 10:59
It crashes on various text segments and in some cases it is due to specific parameter settings. I found, for example that  with -block_ngram_repeat 3 a given text is processed, while with -block_ngram_repeat 2 the summarization fails on the same input. Any feedback would be highly appreciated.

**Comment by sebastianGehrmann** [comment] 2018-09-18 13:58
I will investigate further, but I got this error when I used a beam size that is too small. 
Since we are pruning beams with the repeat condition, it can happen that you run out of beams, which leads to the <blank> repeats. Can you try running the same config with twice as large of a beam?

**Comment by vince62s** [comment] 2018-10-08 18:20
indeed using a beam size of 15 did not trigger the error.
closing for now.

**Closed by vince62s** 2018-10-08 18:20 UTC
Labels: awaiting team, type:bug

**Comment by xinfeng1i** [comment] 2018-10-12 04:07
I got the same problems, when I call `translate.py` script to get inference results, it crashes with the following trackback info:

> Traceback (most recent call last):
>   File "/var/dl/runtime/script/translate.py", line 41, in <module>
>     main(opt)
>   File "/var/dl/runtime/script/translate.py", line 29, in main
>     attn_debug=opt.attn_debug)
>   File "/var/dl/runtime/script/onmt.zip/onmt/translate/translator.py", line 269, in translate
>   File "/var/dl/runtime/script/onmt.zip/onmt/translate/translator.py", line 686, in _report_score
> OverflowError: math range error

In fact, it has infered all the src sentences, when calculate the metrics `PRED AVG SCORE` and `PRED PPL`, it crashes. Any solutions?

**Comment by xinfeng1i** [comment] 2018-11-09 03:09
> Is your task summarization ? can you post your command line ? did you increase the beam ?

@vince62s  Thank you for your reply!  After tracking this issue and reviewing the related code, I can reproduce the error and have found the key reason. There may be a bug in file `translator.py` Line 695, in the funtion `_report_score`。

```
     def _report_score(self, name, score_total, words_total):
        if words_total == 0:
            msg = "%s No words predicted" % (name,)
        else:
            msg = ("%s AVG SCORE: %.4f, %s PPL: %.4f" % (
                name, score_total / words_total,
                name, math.exp(-score_total / words_total)))  #Notice: here is the bug
        return msg
```

The problem is that in a seq2seq translator task, sometimes it may translate a unreadable sentence, which has a really tiny score, in my case I have got: 

> SENT 41697: ('布带',)
> PRED 41697: 吕 布带 战 吕 吕 布带
> PRED SCORE: -1000000020040877342720.0000

Notice that the score is **-1000000020040877342720.0000** , After averaging, the number is still tiny, which will lead the `math.exp` accepting a really large parameter, and therefore got the **OverflowError: math range error**。

In may case, I have tested:
```
>>> import math
>>> avg_score
-3.9033530584366184e+16
>>> math.exp(-avg_score)
Traceback (most recent call last):
  File "<pyshell#178>", line 1, in <module>
    math.exp(-avg_score)
```

I hope someone can fix this problem. In my opinion, the quick way is to ignore any pred score that is really small (meanwhile can logging a warn in the log), and only focus the remaining valid scores.
