### ISSUE TITLE
[feature request]Please add minimal risk training

### ISSUE THREAD

**Issue by SkyAndCloud** [OpenNMT/OpenNMT-py#922] opened 2018-08-26 05:34 UTC
Hi, [minimal risk training](https://arxiv.org/abs/1512.02433) is an effective approach to improve translation score. Could you add this feature into opennmt? Thank you!

**Comment by vince62s** [comment] 2018-08-27 09:29
duplicate of this: http://forum.opennmt.net/t/minimum-risk-training-for-nmt/347

**Closed by vince62s** 2018-08-27 09:29 UTC
