### ISSUE TITLE
Beam search bug

### ISSUE THREAD

**Issue by ketranm** [OpenNMT/OpenNMT-py#137] opened 2017-07-17 23:23 UTC
The output of `translate.py` is inconsistent with different `-batch_size` option. When I trained on IWSLT data and test on ted2013 de->en, the difference is significant, about 9 BLEU between `-batch_size 1` and `-batch_size 30`.

I think one of the culprits is in `Translator.py` https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Translator.py#L201 
When a completed hypothesis is found, we shouldn't advance the beam, otherwise, it will overwrite the best found hypothesis. This can be fixed for example 
```python
def advance(self, wordLk, attnOut):
    return True if self.is_done 
    numWords = wordLk.size(1)
    ...
``` 
at the beginning of `Beam.advance`.

There is still another bug somewhere, I haven't figured out. I would appreciate for any pointer to fix this bug.

**Comment by srush** [comment] 2017-07-17 23:35
Does the issue you describe have to do with batch_size? seems like it would always apply. 

When you get a working model, let's setup an integration test to make sure this dataset remains correct.

**Comment by jekbradbury** [comment] 2017-07-18 02:33
There are lots of ways to write batched beam search that have subtle dependencies on the batch size, typically because they allow the fact that one example in the batch has output an EOS to affect the termination of other examples. I'm not super familiar with the OpenNMT implementation though.

**Comment by srush** [comment] 2017-07-19 22:24
no this is clearly a bug. batch beam search must be identical to regular.

**Comment by jekbradbury** [comment] 2017-07-19 22:34
Is it a bug if the (yes, incorrect) batched beam search implementation gets slightly better BLEU than regular beam search because it's doing some kind of implicit length normalization? Because that's something I've seen before...

**Comment by ketranm** [comment] 2017-07-19 22:46
not sure what do you mean by implicit length normalization. Current OpenNMT-py considers a beam is finished if EOS is generated at the top of the beam. This is also an issue I wonder is there any reason we don't normalize the log probabilities by sentence length as it's done in Google's paper.

**Comment by bpopeters** [comment] 2017-07-22 14:39
I can confirm that results on my multilingual grapheme-to-phoneme task became markedly better when I reduced my batch_size to 1. Discovering this is a big deal for me; it seems to explain a lot of my trouble reproducing my OpenNMT-lua results in python.

**Comment by guillaumekln** [comment] 2017-07-22 17:27
This sounds more like a padding management issue than a beam search issue. The sequence lengths were not passed to the encoder during translation, thus the encoder's states were incorrect.

According to my quick validation test, this is the fix for the issue. Can anyone confirm?

**Comment by srush** [comment] 2017-07-22 17:35
Oh, this sounds right to me.

**Comment by ketranm** [comment] 2017-07-22 17:53
it looks good. I get comparable results now.

**Comment by srush** [comment] 2017-07-22 21:44
Thanks Guilluime. Closing up. Tests coming soon.

**Closed** 2017-07-22 21:44 UTC
Labels: type:bug
