### ISSUE TITLE
Data generation when resuming from a checkpoint

### ISSUE THREAD

**Issue by PC91** [OpenNMT/OpenNMT-py#2517] opened 2023-11-17 06:13 UTC
Hi,
I have a question about the data generation when a training is resumed from a checkpoint.
In the training config file:

- The `batch_type` value is `tokens`.
- The `seed` value is fixed to make the result reproducible.
- The values of `step` and `batches` in the following line of `trainer.py` are observed (by printing to a logging file):

```python
 for i, (batches, normalization) in enumerate(self._accum_batches(train_iter)):

            step = self.optim.training_step
```
I found that the value of `step` changes according to the checkpoint to resume. But this is not the case for `batches`. It seems that a training will always begin with the data generated from the first step even when this training is resumed from a checkpoint. Is there any way to change the configs to have a data generator that adapts to the checkpoint to resume ?

Thank you

**Comment by vince62s** [comment] 2023-11-17 07:57
duplicate of #2006 ?
I recently added an index in the data processed. look here: https://github.com/OpenNMT/OpenNMT-py/pull/2496

actually I have to change the type (no need to be a tensor) but this can be used to achieve restoration of the proper index in datasets.
Do you want to work on this ?

**Comment by PC91** [comment] 2023-11-17 16:24
> duplicate of #2006 ? I recently added an index in the data processed. look here: #2496
> 
> actually I have to change the type (no need to be a tensor) but this can be used to achieve restoration of the proper index in datasets. Do you want to work on this ?

Thanks. I will have a look at it

**Closed** 2023-11-21 10:11 UTC
