### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by TB-SeChaJia** [OpenNMT/OpenNMT-py#929] opened 2018-08-29 12:58 UTC

**Comment by vince62s** [comment] 2018-08-29 12:59
Please provide your pytorch + torchtext version and the command line you used

**Comment by TB-SeChaJia** [comment] 2018-08-29 13:16
torchtext version=="0.2.3"
python3 train.py -data ./output/pre-data/demo

**Comment by bpopeters** [comment] 2018-08-29 14:48
That version of torchtext is out of date. Try running

```
pip install -r requirements.txt
```

and see if things get better (this will also ensure that you're running an up-to-date version of pytorch).

**Comment by vince62s** [comment] 2018-08-29 16:02
duplicate of #930

**Closed by vince62s** 2018-08-29 16:02 UTC
