### ISSUE TITLE
[BUG] dynamic_dict/copy_attn does not work with accum_count > 1

### ISSUE THREAD

**Issue by wasiahmad** [OpenNMT/OpenNMT-py#746] opened 2018-06-05 05:50 UTC
I am getting the following error when I tried to train transformer model on CNNDM dataset for summarization.

> Loading train dataset from data/cnndm/CNNDM.train.3.pt, number of examples: 33018
> Traceback (most recent call last):
>   File "train.py", line 502, in <module>
>     main()
>   File "train.py", line 494, in main
>     train_model(model, fields, optim, data_type, model_opt)
>   File "train.py", line 257, in train_model
>     train_stats = trainer.train(train_iter, epoch, report_func)
>   File "/home/wasiahmad/workspace/projects/OpenNMT-py/onmt/Trainer.py", line 178, in train
>     report_stats, normalization)
>   File "/home/wasiahmad/workspace/projects/OpenNMT-py/onmt/Trainer.py", line 311, in _gradient_accumulation
>     trunc_size, self.shard_size, normalization)
>   File "/home/wasiahmad/workspace/projects/OpenNMT-py/onmt/Loss.py", line 123, in sharded_compute_loss
>     loss, stats = self._compute_loss(batch, **shard)
>   File "/home/wasiahmad/workspace/projects/OpenNMT-py/onmt/modules/CopyGenerator.py", line 191, in _compute_loss
>     batch, self.tgt_vocab, self.cur_dataset.src_vocabs)
>   File "/home/wasiahmad/workspace/projects/OpenNMT-py/onmt/io/TextDataset.py", line 116, in collapse_copy_scores
>     src_vocab = src_vocabs[index]
> IndexError: list index out of range

The training works fine for the first part of the data but whenever it loads the second part (ex., `CNNDM.train.3.pt` file), it gives index out of range error. Any idea what is hapenning? 

I have downloaded the dataset from the link mentioned [here](http://opennmt.net/OpenNMT-py/Summarization.html) and did the preprocessing without any error. Please help.

**Comment by merc85garcia** [comment] 2018-06-19 07:29
Hi, same problem for me. Anyone knows why?

**Comment by wasiahmad** [comment] 2018-06-19 16:48
I tried a lot but couldn't find the reason behind this error.

**Comment by rbommasanimozilla** [comment] 2018-08-03 21:24
@vince62s @wasiahmad what was the eventual resolution?

**Comment by vince62s** [comment] 2018-08-03 21:28
did you try with the lates code + pytorch 0.4 + torchtext 0.3 ?

**Comment by rbommasanimozilla** [comment] 2018-08-03 21:29
i tried it on master as of 3 days ago, currently rerunning now

**Comment by vince62s** [comment] 2018-08-30 10:18
okay, I can replicate this. We'll look into it.

**Comment by vince62s** [comment] 2018-08-30 18:14
Thanks to @pltrdy who helped figuring it out.
The issue is as follow:
When accum_count > 1, when using copy_attn (and therefore dynamic_dict) there is a mismatch if the batches within the "true_batch" = accum_count x batch are accross different shards of the dataset.

For instance, at the end of the first shard, if we have accum_count = 4, we can have 2 batches loaded from the first shard and the last 2 from the second shard.

In this context, we have an issue here: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/copy_generator.py#L195-L197

where self.cur_dataset.src_vocabs may refer to the wrong shard.

This is not easy to solve.

In the meantime, use only accum_count = 1 with copy_attn and if you can use more GPU.

I have tried to go back in time and in fact it seems to have never worked.
So I am a bit confused that the tuto specification with copy_attn + accum_count = 4

@srush  @sebastianGehrmann  can you check the config of the model you posted for summarization ?

Thanks.

**Comment by vince62s** [comment] 2018-09-03 12:02
fixed in #938

**Closed by vince62s** 2018-09-03 12:02 UTC
Labels: awaiting team, contributions welcome, type:bug
