### ISSUE TITLE
Torchtext v0.2 issue

### ISSUE THREAD

**Issue by laubonghaudoi** [OpenNMT/OpenNMT-py#345] opened 2017-10-18 04:27 UTC
I followed the instructions in Quickstart to train the model, and after training some time it showed the following errors, it there any way to solve it ?
```
Epoch  1,    50/  157; acc:   3.77; ppl: 111362.48; 200 src tok/s; 201 tgt tok/s;    356 s elapsed
Epoch  1,   100/  157; acc:   6.40; ppl: 21387.26; 217 src tok/s; 214 tgt tok/s;    692 s elapsed
Epoch  1,   150/  157; acc:   7.70; ppl: 4699.85; 218 src tok/s; 217 tgt tok/s;   1021 s elapsed
Train perplexity: 20880.5
Train accuracy: 6.0594
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    main()
  File "train.py", line 295, in main
    train_model(model, train, valid, fields, optim)
  File "train.py", line 160, in train_model
    valid_stats = trainer.validate()
  File "/home/user/Documents/OpenNMT-py/onmt/Trainer.py", line 155, in validate
    outputs, attns, _ = self.model(src, tgt, src_lengths)
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Documents/OpenNMT-py/onmt/Models.py", line 417, in forward
    enc_hidden, context = self.encoder(src, lengths)
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Documents/OpenNMT-py/onmt/Models.py", line 94, in forward
    packed_emb = pack(emb, lengths)
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 79, in pack_padded_sequence
    raise ValueError("lengths array has to be sorted in decreasing order")
ValueError: lengths array has to be sorted in decreasing order
```

**Comment by JianyuZhan** [comment] 2017-10-20 06:58
Duplicate of #189, the new `torchtext v0.2` has addressed this problem.

**Comment by laubonghaudoi** [comment] 2017-10-20 08:02
I have upgraded my torchtext to 0.2.0 and this issue still exists, please reopen this issue.

**Comment by JianyuZhan** [comment] 2017-10-20 08:44
@laubonghaudoi , seems we need some modification based on `torchtext 0.2.0` as well.

I didn't encounter this problem in my environment, could you help test if this patch helps solve this problem?  If you encounter any problem, please post the trackback.

```
diff --git a/onmt/IO.py b/onmt/IO.py
index f67ccdc..f635d0e 100644
--- a/onmt/IO.py
+++ b/onmt/IO.py
@@ -107,8 +107,8 @@ class ONMTDataset(torchtext.data.Dataset):
 
     @staticmethod
     def sort_key(ex):
-        "Sort in reverse size order"
-        return -len(ex.src)
+        "Sort by length of sentences."
+        return len(ex.src)
 
     def __init__(self, src_path, tgt_path, fields, opt,
                  src_img_dir=None, **kwargs):
diff --git a/train.py b/train.py
index eb102b4..7e25877 100644
--- a/train.py
+++ b/train.py
@@ -94,10 +94,12 @@ def make_train_data_iter(train_data, opt):
     ordered iterator strategy here, but more sophisticated strategy
     like curriculum learning is ok too.
     """
+    # Sort batch by decreasing lengths of sentence required by pytorch.
+    # sort=False here means "Using dataset's sortkey not iterator.sortkey.
     return onmt.IO.OrderedIterator(
                 dataset=train_data, batch_size=opt.batch_size,
                 device=opt.gpuid[0] if opt.gpuid else -1,
-                repeat=False)
+                sort=False, sort_within_batch=True, repeat=False)
 
 
 def make_valid_data_iter(valid_data, opt):
diff --git a/translate.py b/translate.py
index 245c947..88d7f67 100644
--- a/translate.py
+++ b/translate.py
@@ -60,7 +60,7 @@ def main():
     test_data = onmt.IO.OrderedIterator(
         dataset=data, device=opt.gpu,
         batch_size=opt.batch_size, train=False, sort=False,
-        shuffle=False)
+        sort_within_batch=True, shuffle=False)
 
     counter = count(1)
     for batch in test_data:
```

**Comment by laubonghaudoi** [comment] 2017-10-23 00:50
I run this patch and it works fine now, thank you very much.

**Comment by thammegowda** [comment] 2017-10-24 01:35
I hit the same error today. This happened with `torchtext (0.2.0a0)` and `torch (0.2.0.post4)` with default installation

I just downgraded torchtext with `pip install torchtext==0.1.1` as a temporary/quick fix, it works. 

Going forward:
1.  the code should be patched with the above patch https://github.com/OpenNMT/OpenNMT-py/issues/345#issuecomment-338145520
OR
2. requirements.txt should force the torchtext==0.1.1

**Comment by jekbradbury** [comment] 2017-10-24 07:00
Since we'd already made the decision to change the sort behavior in torchtext source, and some people had started to rely on that, we basically had to break things slightly for either 0.1 users/ONMT or source users. Sorry about that; hopefully the two issues from 0.1.1 -> 0.2 can be resolved quickly.

**Comment by donglixp** [comment] 2017-10-27 21:31
Add ``sort_within_batch=False'' as follows will fix this issue.

```python
valid_iter = table.IO.OrderedIterator(
        dataset=valid_data, batch_size=opt.batch_size, device=opt.gpuid[0], train=False, sort=True, sort_within_batch=False)
```

**Comment by caozhen-alex** [comment] 2017-11-03 02:57
@donglixp  Thx for the answer. But, it seems no $"valid_iter = table.IO.OrderedIterator(
        dataset=valid_data, batch_size=opt.batch_size, device=opt.gpuid[0], train=False, sort=True, sort_within_batch=False)"$ in the train.py file

**Comment by caozhen-alex** [comment] 2017-11-03 02:58
@laubonghaudoi  Excuse me, how can I run that bath?

**Comment by JianyuZhan** [comment] 2017-11-03 05:46
@caozhen-alex ,  copy the text and save it into a file like `foo.patch`,  then put it in the root directory of the project and do `patch -p1 < foo.patch`.

**Comment by donglixp** [comment] 2017-11-03 13:52
@caozhen-alex It's line 113 in train.py: https://github.com/OpenNMT/OpenNMT-py/blob/master/train.py#L113

**Comment by caozhen-alex** [comment] 2017-11-06 01:34
@donglixp  Thx Li Dong.

**Comment by caozhen-alex** [comment] 2017-11-06 01:36
@JianyuZhan Thx, Jianyu. Thank you for your instrument. Heard this kind of stuff first time.

**Comment by JianyuZhan** [comment] 2017-11-06 05:35
@caozhen-alex ,  the problem in this issue is due to some change in the new version of `torchtext`(our project depends on it), so our project need fix to accommodate this change.

The code is generated by `git diff`, which shows code difference between the base version and the modified version, and the diff is usually called `patch`, and it can be patch into base version by the tool `patch`.

**Comment by caozhen-alex** [comment] 2017-11-06 07:08
@JianyuZhan  Thank you very much for your patience and clear explanation!

**Comment by JianyuZhan** [comment] 2017-12-17 10:35
Hello, @jekbradbury ,  is the fix available on PyPI?  If yes, we will resolve the problems on our side.

**Closed** 2017-12-27 19:22 UTC
Labels: type:bug

**Comment by happycjksh** [comment] 2021-07-15 07:55
@laubonghaudoi Could you tell me how to solve the problem?

**Comment by happycjksh** [comment] 2021-07-15 08:00
My version is 0.2.3, but I encounter this problem

**Comment by laubonghaudoi** [comment] 2021-07-15 08:07
> @laubonghaudoi Could you tell me how to solve the problem?

This issue is from four years ago, I have completely forgot how I made it
