### ISSUE TITLE
freeze partial networks

### ISSUE THREAD

**Issue by i55code** [OpenNMT/OpenNMT-py#1895] opened 2020-10-20 17:51 UTC
Hi all, is there a functionality that enables the network to freeze the encoder/decoder/output layer to finetune a big model? I know some other platforms have incorporated that into their system, would OpenNMT team consider it? And if there is no existing ones, can you point to the code pieces ? Thanks!

**Comment by francoishernandez** [comment] 2020-10-21 08:26
Duplicate of #1857 , replying there.

**Closed by francoishernandez** 2020-10-21 08:26 UTC
