### ISSUE TITLE
ValueError: lengths array has to be sorted in decreasing order

### ISSUE THREAD

**Issue by xjtu-zeng** [OpenNMT/OpenNMT-py#395] opened 2017-11-28 12:47 UTC
I just clone the latest version and run the provided demo command.
I noticed that the lengths of the batch_src in valid is increasing which are not suited to pack_padded_sequence.

**Comment by xjtu-zeng** [comment] 2017-11-28 13:20
I just fix it by change **sort = False**, do you guys have the same error?
![image](https://user-images.githubusercontent.com/15373554/33321776-d183be66-d481-11e7-889c-eef57baf07e2.png)

**Comment by JianyuZhan** [comment] 2017-11-29 07:08
Seems duplicate of https://github.com/OpenNMT/OpenNMT-py/issues/345

**Comment by JianyuZhan** [comment] 2017-11-30 01:40
Close since we have one open issue for the same problem. We will get this fixed when torchtext issued is solved.

**Closed by JianyuZhan** 2017-11-30 01:40 UTC

**Comment by bobobe** [comment] 2019-01-02 15:50
你好，能不能告知一下你的torchtext和pytorch版本，我用python3.5和torchtext0.2.3,pytorch0.3.1和楼上是一样的错误。

**Comment by hongweizeng** [comment] 2019-01-03 03:11
我不记得当时的版本了，现状应该是修复好了吧，最新的OpenNMT，torchtext0.3.1，pytorch1.0。

**Comment by happycjksh** [comment] 2021-07-15 07:23
我也遇到了同样的问题，请问你们最终是如何解决的？

**Comment by happycjksh** [comment] 2021-07-15 07:46
I have the same problem in torchtext version=0.2.3, I've already pype all versions you mentioned in #345, but I can't solve it. Can you help me?
