### ISSUE TITLE
Massive memory use because entire file is slurped in IO.py

### ISSUE THREAD

**Issue by aryamccarthy** [OpenNMT/OpenNMT-py#283] opened 2017-09-20 18:16 UTC
Is there a strong reason for slurping the entire source file in `translate.py`? On a source file of 2M single-character-per-token sentences, memory usage exceeds 256 GB. I figure that since evaluation is sentence-by-sentence (or batch-by-batch), this can be avoided.

Lab-mates and I have written an [`itertools.islice`](https://docs.python.org/3/library/itertools.html#itertools.islice)-based workaround. I'm happy to convert it into a PR if I have more information about the design goals and decisions, so I don't step on toes.

**Comment by srush** [comment] 2017-09-20 21:14
Huh, not sure why it is doing this. It reads in the whole file, but only constructs the matrices for a batch at a time. Not sure why it is taking up so much memory. We will look into it.

**Comment by aryamccarthy** [comment] 2017-09-20 21:16
Thanks. I'm happy to work on it, Sasha. Is it on OpenNMT's side or PyTorch's?

**Comment by srush** [comment] 2017-09-20 21:24
Yeah, we would love to have more contributions. That would be great. 

It's likely on our side. This line https://github.com/OpenNMT/OpenNMT-py/blob/master/translate.py#L84 does read in all the examples as text. But I can't imagine that would take 256 GB. Can you check if that line alone does it?

**Comment by aryamccarthy** [comment] 2017-09-20 21:39
My sysadmin wouldn't like it if I tried the code again. My guess is that it happens inside that initializer, on [this line](https://github.com/OpenNMT/OpenNMT-py/blob/b08b56966d4c495c904a1bddc4319d0bfeecbf47/onmt/IO.py#L203) that constructs a list. I'll investigate what would happen if it were replaced with a generator.

**Comment by srush** [comment] 2017-09-21 20:40
Sounds like this is your issue @vince62s

**Comment by vince62s** [comment] 2017-09-21 20:44
same issue ? mine was in preprocess.py, similar code ?

**Comment by srush** [comment] 2017-09-21 21:01
Yeah, it's the same code. Think someone changed something recently. Investigating.

**Comment by srush** [comment] 2017-09-21 21:52
Think this should help https://github.com/OpenNMT/OpenNMT-py/pull/289 . Working on the file saving part.

**Comment by bpopeters** [comment] 2017-09-24 19:43
Using a lazy iterator for the examples, as in #289, will only work if `filter_pred` is `None`, and at the moment that's only the case if `opt` is also `None`. See the constructor of `ONMTDataset`'s [parent class](https://github.com/pytorch/text/blob/master/torchtext/data/dataset.py#L36). Whatever benefit you gain from the generator, you lose the moment it's loaded into the list.

**Comment by srush** [comment] 2017-09-25 20:16
I don't think that is true. The code before was creating multiple objects of the size of the data. The constant factor matters a lot here.

**Comment by bpopeters** [comment] 2017-09-25 20:27
You're right, saying that all the benefits are lost is incorrect. I was thinking based on the assumption that the whole-file slurping was the problem, but you're right, the problem was actually all the auxiliary data structures that we got rid of.

**Comment by srush** [comment] 2017-09-25 20:32
Actually, not really sure what the problem is. Possibly that the data structure of example is memory inefficient? Maybe ever having them all in memory is bad.

**Comment by jan-rosendahl** [comment] 2017-10-26 10:10
I encounter the same problem ( namely: I use preprocess.py to handle a corpus with 10M sentences and memory consumptions goes up to 30 GB before I kill it).

It seems that the problem is caused in https://github.com/OpenNMT/OpenNMT-py/blob/9f4b4d77caf553d317af9b7bba4e7a9634253bf0/onmt/IO.py#L156-L157

When I start the program it runs up to that point, never continues but keeps allocating memory

**Comment by bpopeters** [comment] 2017-10-26 10:25
I concur about zip. Are you using 2 or 3?

**Comment by jan-rosendahl** [comment] 2017-10-26 10:30
I used python2 so far. I am just about to try python3. Is there a recommendation for OpenNMT-py?

**Comment by bpopeters** [comment] 2017-10-26 10:56
We're trying to keep it functional with both. The problem is that there are a bunch of cases where the semantics of built-ins changed between 2 and 3, and lots of stuff that used to return a list returns an iterator now. These are hard to catch because the output is the same, it's just the memory use that's different. You found one of these, and I think your `itertools.izip` solution is correct. Feel free to submit a pull request, although it probably won't get merged right away something weird is going on with our testing and I haven't heard from @srush in a while.

As for the continuing memory problems, it's possible there are more cases analogous to this. Switching to python3 might help with some of these. However, if I recall there's also some potentially troublesome code in torchtext, which we're using for the IO. I'll look in to it when I get the chance.

**Comment by jan-rosendahl** [comment] 2017-10-26 12:59
I can do that however just replacing the zip is not enough in my case.

Next I encounter the same memory problems in
https://github.com/OpenNMT/OpenNMT-py/blob/9f4b4d77caf553d317af9b7bba4e7a9634253bf0/onmt/IO.py#L196-L200

which leads to the execution of the lines in Torch: site-packages/torchtext/data/dataset.py:
```
class Dataset(torch.utils.data.Dataset): 
    ... 
    def __init__(self, examples, fields, filter_pred=None):
       ...
       if filter_pred is not None:
            examples = list(filter(filter_pred, examples))
```
setting the filters to None fixes the problem for me (Test still running) but of course changes the behaviour.

**Comment by jan-rosendahl** [comment] 2017-10-26 14:11
ok. To summarize this: I can use [six](https://pythonhosted.org/six/#module-six.moves)  and add `from six.moves import zip` to remove problems with the python2/3 storage difference in zip.

Then I still have the problem that if filter_pred is not None I run into memory issues. If I resolve this (by deleting filter_pred) I cant save my model (using python 3.5.2) because of:
```
Traceback (most recent call last):
  File "/XYZ/OpenNMT-py/preprocess.py", line 78, in <module>
    main()
  File "/XYZ/OpenNMT-py/preprocess.py", line 73, in main
    torch.save(train, open(opt.save_data + '.train.pt', 'wb'))
  File "ABC/lib/python3.5/site-packages/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/ABC/lib/python3.5/site-packages/torch/serialization.py", line 186, in _save
    pickler.dump(obj)
TypeError: can't pickle generator objects
```

I can put this in to a pull request but as I end up with a version that is not working I am not sure if I should do this.

**Comment by IdiosyncraticDragon** [comment] 2017-11-01 08:40
@vince62s I think I met the same problem.
Preprocess.py 2 files (1.7 G and 2.0G, WMT14 En->Fr), the memory (32G free RAM) was exhausted and the process was idle. I found that use preprocess.lua in Opennmt project would not perform like this. Can I use preprocess.lua in Opennmt to proprocess the data and train the model using Opennmt-py?

**Comment by IdiosyncraticDragon** [comment] 2017-11-09 03:11
I had preprossed the data of WMT14-EN-FR(1.7G and 2.0G individually) and resulted in train.pt with 17G, and when I load it into memory for training, it consumes 238G in total. Does It seem like some types of memory leak? Here is my script of preprocessing:
`
python preprocess.py -train_src /home/lgy/data/wmt/wmt14-en-fr/training-en.tok -train_tgt /home/lgy/data/wmt/wmt14-en-fr/training-fr.tok -valid_src /home/lgy/data/wmt/wmt14-en-fr/val-en.tok -valid_tgt /home/lgy/data/wmt/wmt14-en-fr/val-fr.tok -save_data /home/lgy/data/wmt/wmt14-en-fr/pywmt14 -src_vocab_size 30000 -tgt_vocab_size 30000 -src_seq_length 1000 -tgt_seq_length 1000 -dynamic_dict
`

**Comment by caleblu** [comment] 2017-12-06 22:43
Yeah I have the same problem. When I loaded the model for training, it consumed far larger memory that the file size. Any suggestions?

**Comment by playma** [comment] 2017-12-19 07:37
@srush Have this problem been solved? 
I face the same problem.

**Comment by srush** [comment] 2017-12-20 22:47
Yeah, sorry this is our number one issue right now. @JianyuZhan is on it. There is currently a pull request to support sharding. It should be available soon.

**Comment by playma** [comment] 2017-12-21 02:28
@srush  @JianyuZhan Thank you for your effort.
I thought that you can refer to the works below: 

https://github.com/tensorflow/nmt
https://github.com/facebookresearch/fairseq-py/

I have tried this two work, and it works and very fast.

**Comment by srush** [comment] 2018-02-19 20:17
This is fixed now.

**Closed by srush** 2018-02-19 20:17 UTC
Labels: type:bug

**Comment by xforceco** [comment] 2018-02-21 08:55
May I know which pull request solving this?

**Comment by srush** [comment] 2018-02-21 14:33
We added sharding to the preprocess.py script. Use `-max_shard_size` to split the file into shard each of which are loaded one at a time.

**Comment by xforceco** [comment] 2018-02-21 15:13
Great, thanks for this option.
Probably this can be added to the documentation page: 
http://opennmt.net/OpenNMT-py/options/preprocess.html
