### ISSUE TITLE
Segmentation fault after applying subwords methods

### ISSUE THREAD

**Issue by aastha19** [OpenNMT/OpenNMT-py#1625] opened 2019-11-04 04:48 UTC
You need to apply some subwords methods. Have look [here](http://forum.opennmt.net/t/using-sentencepiece-byte-pair-encoding-on-model/3027).

_Originally posted by @francoishernandez in https://github.com/OpenNMT/OpenNMT-py/issues/1617#issuecomment-547785127_

@francoishernandez  I applied OpenNMT Tokenizer to the dataset. It reduced the dictionary size but still, Segmentation Fault (core dumped) occurs. 
Could you let me know if there is any other way to deal with it?

**Comment by francoishernandez** [comment] 2019-11-04 07:59
Duplicate of #1617 
(Please do not open another issue when the discussion is already happening in one.)

**Closed** 2019-11-04 08:00 UTC
