### ISSUE TITLE
Missing documentation in beam_update

### ISSUE THREAD

**Issue by shubhamagarwal92** [OpenNMT/OpenNMT-py#787] opened 2018-06-30 14:20 UTC
In [beam_update](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/decoder.py#L393) we are missing documentation. 

Also, how do we handle the sequences which see EOS earlier like done [here](https://github.com/IBM/pytorch-seq2seq/blob/master/seq2seq/models/TopKDecoder.py#L257).             (Although the ended sequences are dropped during decoding, their generated symbols and complete backtracking information are still in the backtracking variables.) We are basically doing the same thing [here](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/beam.py#L98); not letting EOS have children but also appending their information in corresponding lists. 

Can you explain the code in more detail and how do I use the beam search as a standalone module in my decoder implementation.

**Comment by vince62s** [comment] 2018-09-03 14:57
duplicate of #742

**Closed by vince62s** 2018-09-03 14:57 UTC
Labels: type:question
