### ISSUE TITLE
translate.py with a transformer model

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#281] opened 2017-09-20 11:58 UTC
Do I need to specify somehting special? here is my error for the follwoing command line:
python3 translate.py -gpu 1 -model baseline-1M.fr-en_acc_69.66_ppl_5.18_e13.pt \
    -src $TEST_SRC -output $TEST_HYP.tok -beam_size $bs -batch_size 1

Loading model
While copying the parameter named decoder.embeddings.make_embedding.pe.pe, whose dimensions in the model are torch.Size([5000, 1, 512]) and whose dimensions in the checkpoint are torch.Size([5000, 1, 512]), ...
Traceback (most recent call last):
  File "translate.py", line 153, in <module>
    main()
  File "translate.py", line 77, in main
    translator = onmt.Translator(opt, dummy_opt.__dict__)
  File "/home/pytorchwork/OpenNMT-py/onmt/Translator.py", line 29, in __init__
    model_opt, self.fields, use_gpu(opt), checkpoint)
  File "/home/pytorchwork/OpenNMT-py/onmt/ModelConstructor.py", line 161, in make_base_model
    model.load_state_dict(checkpoint['model'])
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
  File "/usr/local/lib/python3.5/site-packages/torch/autograd/variable.py", line 65, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'copy_'

**Comment by JianyuZhan** [comment] 2017-09-20 12:01
See https://github.com/OpenNMT/OpenNMT-py/issues/256. 

I also can reproduce this problem and use the patch I posted in that issue, it is solved. I am not sure if it can solve your problem,  please reply to that issue to confirm this, thanks !

**Comment by vince62s** [comment] 2017-09-20 12:12
another error

Loading model
While copying the parameter named decoder.embeddings.make_embedding.pe.pe, whose dimensions in the model are torch.Size([5000, 1, 512]) and whose dimensions in the checkpoint are torch.Size([5000, 1, 512]), ...
Traceback (most recent call last):
  File "translate.py", line 153, in <module>
    main()
  File "translate.py", line 77, in main
    translator = onmt.Translator(opt, dummy_opt.__dict__)
  File "/home/pytorchwork/OpenNMT-py/onmt/Translator.py", line 29, in __init__
    model_opt, self.fields, use_gpu(opt), checkpoint)
  File "/home/pytorchwork/OpenNMT-py/onmt/ModelConstructor.py", line 161, in make_base_model
    model.load_state_dict(checkpoint['model'])
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: copy from Variable to torch.FloatTensor isn't implemented

**Comment by JianyuZhan** [comment] 2017-09-20 12:14
This is because you don't re-train after patching, the previous one is still `Variable`. Re-train will solve this.

**Comment by vince62s** [comment] 2017-09-20 12:16
you mean re-train completely my model ? or just load it and train another step ?

**Comment by JianyuZhan** [comment] 2017-09-20 12:18
yep, retrain the model, or to validate if it works, you can train a small model with few epochs first.

**Comment by vince62s** [comment] 2017-09-20 13:35
okay I trained 1 epoch, it works with this patch.
is there a reason why it's problematic only for the transformer and not the rnn model ?

**Comment by JianyuZhan** [comment] 2017-09-20 13:43
Is it only happened on transformer?  Did you specify the `-position-encoding` option?  I think it is because most people use this option with transformer, because it is in the paper proposes transformer.

BTW, would you please reply to that issue ? That would help people who also encounter this issue.

**Comment by vince62s** [comment] 2017-09-20 13:56
what do you mean ? why don't you commit your patch ?

**Comment by JianyuZhan** [comment] 2017-09-20 13:58
Okay. I will, I just want to make sure it fixes things, not only on my settings. Thanks ~

**Comment by JianyuZhan** [comment] 2017-09-21 02:35
Fixed in https://github.com/OpenNMT/OpenNMT-py/commit/dffd1311604cbc9396500418f326dfe4fc5a6f96

**Closed by JianyuZhan** 2017-09-21 02:35 UTC
