### ISSUE TITLE
Translate.py error after adding feature embedding

### ISSUE THREAD

**Issue by wwhgh** [OpenNMT/OpenNMT-py#474] opened 2017-12-24 08:07 UTC
The training and testing data have the same format. 
After adding feature embedding, the translate.py will have the same error with #388.
It seem the problem of size, but how can I solve it ? 
Thank you !

**Comment by JianyuZhan** [comment] 2017-12-27 11:57
The translation code has just been refactored, can you run on the latest code and post the trackback and 
your full parameter settings?  If you can provide a run-able reproducer, that would be great.

**Comment by wwhgh** [comment] 2017-12-28 09:23
Thank you! @JianyuZhan 

I have used the latest code of all project. 
The format of all files are :

> a￨f1 b￨f2 a￨f1 ...

The parameter of _translate.py_ is:

> -model models/best.pt -src src-test.txt -output pred.txt -replace_unk -verbose 

The trace back is:

>  Traceback (most recent call last):
  File "translate.py", line 116, in <module>
    main()
  File "translate.py", line 79, in main
    batch_data = translator.translate_batch(batch, data)
  File "*/onmt/translate/Translator.py", line 141, in translate_batch
    inp, context, dec_states, context_lengths=context_lengths)
  File "*/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "*/onmt/Models.py", line 259, in forward
    input, context, state, context_lengths=context_lengths)
  File "*/onmt/Models.py", line 446, in _run_forward_pass
    emb = self.embeddings(input)
  File "*/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "*/onmt/modules/Embeddings.py", line 179, in forward
    aeq(nfeat, len(self.emb_luts))
  File "*/onmt/Utils.py", line 11, in aeq
    "Not all arguments have the same value: " + str(args)
AssertionError: **Not all arguments have the same value:** (1, 2)

But if I change all the files format into

>  abc￨f1 bcd￨f2 aef￨f1 

The _translate.py_  works well. 

How to solve it?

**Comment by JianyuZhan** [comment] 2017-12-28 11:16
Well, this is the desired text format:

```
Every lines consists of "words" + (optional) u"￨"-delimited features
```

**Comment by hubert0527** [comment] 2017-12-31 17:17
Hi @JianyuZhan,

I have the same issue too. (I'm sure I'm up to date with OpenNMT master)
I tried several different combinations of input/output features (e.g. "input 0 feature, output 1 feature", "input 1 feature, output 1 feature"), but all of them are throwing the same error:
```
AssertionError: Not all arguments have the same value: (1, 2)
```

#### My train.src:

```
aa
bb
cc
```

#### My train.tgt:

```
1234￨abcd 5678￨qqqq
2345￨bcde 3456￨wwww
3456￨cdef 1234￨eeee
```

This is just a testcase.
It can run through training phase smoothly, but keeps throwing AssertionError during translation phase.
I even tried to use the same train.tgt as all train.src/train.tgt/test.src/test.tgt at the same time.
But it does not work too.

Please kindly point me out if I misunderstood anything :)
Thanks!

**Comment by JianyuZhan** [comment] 2018-01-03 12:38
@wwhgh @hubert0527 

I haven't tested corpus with features, would you please provide me some demo corpus to reproduce this problem?  I will spend some time investigating it then.

**Comment by hubert0527** [comment] 2018-01-03 12:49
Hi @JianyuZhan ,

I think my train.src/train.tgt example above should theoretically work (although it's kind of meaningless).
Or "copy & paste from source to target" task can also be a good testcase.

Thanks!

**Comment by JianyuZhan** [comment] 2018-01-03 12:52
@hubert0527, okay, I will try to reproduce it .

**Comment by hubert0527** [comment] 2018-01-03 16:22
Hi @JianyuZhan ,

I'm now also debugging on this, and found something interesting.
My testcase for translation is here:

**src**
```
aa
bb
cc
dd
```
**tgt** (just an expected output format)
```
aa￨123 aa￨123
bb￨123 bb￨123
cc￨123 cc￨123
dd￨123 dd￨123
```

During run time, **Translator.translate_batch()** will first run **"self.model.encoder"**, then **"self.model.decoder"**.
And I looked into the input run time size:
a. Inside "self.model.encoder", the input size is (1, 4, 1), which is (in_length, in_batch, nfeat).
b. Inside "self.model.decoder", the input size is (1, 20, **1**). The 20 here is in_batch(4)*beam_size(5).

We can see that the "nfeat" of decoder input is already wrong.
But I'm not sure how OpenNMT implement beam search when there's extra features, so it's hard for me to directly fix it.

Hope this can be a piece of helpful information.
Thanks!

**Comment by ykasimov** [comment] 2018-01-08 13:20
I have the same issue. 
I have trained a model where src and tgt data has one feature. 
When I use the same data for translation, I get the same error. 

I tried to train another model using test data:
source:
`aa￨123 aa￨123
bb￨123 bb￨123
cc￨123 cc￨123
dd￨123 dd￨123`

target:
`aa￨123 aa￨123
bb￨123 bb￨123
cc￨123 cc￨123
vv￨123 vv￨123`

I was able to use this new model to translate the source test data.

**Comment by JianyuZhan** [comment] 2018-01-08 13:45
@hubert0527 , sorry I was distracted by other things recently.  Thanks for your hint,  I will continue investigation this week.

**Comment by ykasimov** [comment] 2018-01-08 16:00
Hi, 

I have the same problem.

I noticed that although I have features in my train/validation data, the field 'src_feat_n'/'tgt_feat_n' is missing from the fields variable.

After investigation, I found a problem in DatasetBase.py_ on line 103:

`split_tokens = [t.split(u"|") for token in tokens]`

In my case _tokens_ looks like that:
`tokens = ['aaa|C', 'bbb|L']`

for some reason _split_tokens_ is:
`split_tokens = [['aaa|C'], ['bbb|L']]`

After I have changed double quotes to single quotes in split method on line 103 :
``split_tokens = [t.split('|') for token in tokens]``
_split_tokens_ is correct:
``split_tokens = [['aaa','C'], ['bbb,'L']]``

I re-did preprocessing of my data and trained a small model. I was able to translate without the error.

**Comment by ykasimov** [comment] 2018-01-19 13:14
Hi guys, 
Any update regarding this problem?
Thanks.

**Comment by hubert0527** [comment] 2018-01-19 13:40
I guess it's not easy to solve.
I am running my project on OpenNMT-lua now, it's feature embedding can work.

**Comment by XinnuoXu** [comment] 2018-02-08 16:37
I met the same problem. Any updates?

**Comment by srush** [comment] 2018-02-08 18:33
@da03 can you look into this? I thought your feature embedding was working.

**Comment by da03** [comment] 2018-02-08 21:05
Yeah sure I'll look into that. I was only using source side embedding before.

**Comment by srush** [comment] 2018-02-08 21:36
Oh! I don't think we ever implemented target side embeddings. I didn't realize that was the issue. 

Maybe @bpopeters did this?

**Comment by bpopeters** [comment] 2018-02-08 22:08
I eliminated a couple bits of IO and decoder code that were making it unnecessarily difficult to implement target features in the future, but I never actually implemented them.

**Comment by XinnuoXu** [comment] 2018-02-09 00:26
I see. So, it means that only source side feature embedding is working?

**Comment by XinnuoXu** [comment] 2018-02-09 00:28
Well, it makes sense. Target side feature embedding is harder to implement considering the beam search : )

**Comment by srush** [comment] 2018-02-09 04:08
We will add it to the roadmap. I think @da03 will need it for his project, and all the plumbing is there already so it shouldn't be so bad. Let us know if you want to help out. To start with we will just need a separate generator class and loss function. Then we can consider adding it to beam search.

**Comment by soumyagk** [comment] 2018-03-17 09:06
I encountered the same error during translation. My source sentences contain 2 features (training was performed with source having 2 features per token and target having 1 per token).  The exception stack is as below:
```
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main()
  File "translate.py", line 105, in main
    batch_data = translator.translate_batch(batch, data)
  File "/home/soumya/OpenNMT-py/onmt/translate/Translator.py", line 135, in translate_batch
    inp, memory_bank, dec_states, memory_lengths=memory_lengths)
  File "/home/soumya/OpenNMT-py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/soumya/OpenNMT-py/onmt/Models.py", line 313, in forward
    tgt, memory_bank, state, memory_lengths=memory_lengths)
  File "/home/soumya/OpenNMT-py/onmt/Models.py", line 481, in _run_forward_pass
    emb = self.embeddings(tgt)
  File "/home/soumya/OpenNMT-py/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/soumya/OpenNMT-py/onmt/modules/Embeddings.py", line 179, in forward
    aeq(nfeat, len(self.emb_luts))
  File "/home/soumya/OpenNMT-py/onmt/Utils.py", line 11, in aeq
    "Not all arguments have the same value: " + str(args)
AssertionError: Not all arguments have the same value: (1, 2)
``` 
Debugging led me to this line being the main point where the embedding dimensions are being changed:
https://github.com/OpenNMT/OpenNMT-py/blob/ea254b1b9c9aa8804b9fb4c6b688c63f00b664db/onmt/translate/Translator.py#L137
`            inp = inp.unsqueeze(2)`
It forcibly adds a tensor of size 1 at position 2, making the tensor [1, 150] to [1,150, 1] .
Here the 3 dimensions in [1, 150, 1] are later on unzipped as input length, input batch size and number of features. This number of features should be 2 in my case (from my understanding - but I may be wrong). 
Any help on this appreciated!

**Comment by tuyethai** [comment] 2018-06-04 06:21
Hi,
I have the same problem with translate.py after adding source side feature embeddings. 
The input format is: word1￨feat1 word2￨feat2 ...
Could you please give me any suggestions to solve it? Thank a lot.

**Comment by vince62s** [comment] 2018-08-04 16:08
closing this.
I opened a project "Support for target side features"

**Closed by vince62s** 2018-08-04 16:08 UTC

**Comment by eduamf** [comment] 2019-04-23 14:55
The project  "Support for target side features" is empty.

**Comment by eduamf** [comment] 2019-04-28 15:34
> Oh! I don't think we ever implemented target side feature embeddings. I didn't realize that was the issue.
> 
> Maybe @bpopeters did this?

The error occurs even though the target value is empty.
