### ISSUE TITLE
Support oracle decoding with copy attention.

### ISSUE THREAD

**Issue by abhishek0318** [OpenNMT/OpenNMT-py#756] opened 2018-06-09 18:15 UTC
I get the following error if I specify the true target (`tgt` argument)  in `translate.py`, if I am using CopyGenerator i.e. `copy_attn` argument in `train.py`. 

```
  prob = F.softmax(logits)
Traceback (most recent call last):
  File "translate.py", line 29, in <module>
    main(opt)
  File "translate.py", line 18, in main
    opt.batch_size, opt.attn_debug)
  File "/home/abhisha/OpenNMT-py/onmt/translate/Translator.py", line 159, in translate
    batch_data = self.translate_batch(batch, data)
  File "/home/abhisha/OpenNMT-py/onmt/translate/Translator.py", line 339, in translate_batch
    ret["gold_score"] = self._run_target(batch, data)
  File "/home/abhisha/OpenNMT-py/onmt/translate/Translator.py", line 384, in _run_target
    out = self.model.generator.forward(dec)
TypeError: forward() missing 2 required positional arguments: 'attn' and 'src_map'
```
This is because CopyGenerator requires `attn` and `src_map`  parameters to generate the output, which are not available which translating.

To solve the problem, we could ignore computing Gold Scores if CopyGenerator is used. Solving the issue completely would require a lot of changes in the code.

**Comment by sebastianGehrmann** [comment] 2018-06-09 22:35
Since it is not trivial how to exactly compute the score, we have not implemented it and I recommend that you run the translate.py without specifying targets. In the future, we should print a warning when someone uses these two in combination.

**Comment by vince62s** [comment] 2018-09-03 12:51
duplicate of #425

**Closed by vince62s** 2018-09-03 12:51 UTC
Labels: type:feature
